name: CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create NuGet Package
        run: dotnet pack ./working
         
      - name: Find created nuget
        id: findcreatednuget        
        run: echo nugetPackageName=$(find . -type f -name '*.nupkg') >> $GITHUB_OUTPUT
        shell: bash
        
      - uses: actions/upload-artifact@v4
        with:
          name: NugetPackages
          path: "${{ steps.findcreatednuget.outputs.nugetPackageName }}"