name: CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create NuGet Package
        run: dotnet pack ./working
         
      - name: Find created nuget
        id: findcreatednuget        
        run: echo nugetPackageName=$(find . -type f -name '*.nupkg') >> $GITHUB_OUTPUT
        shell: bash
        
      - uses: actions/upload-artifact@v4
        with:
          name: NugetPackages
          path: "${{ steps.findcreatednuget.outputs.nugetPackageName }}"

  push:
    if: github.ref_type == 'tag'
    name: push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download NuGet
        id: downloadNuGet
        uses: actions/download-artifact@v4
        with:
          name: NugetPackages
          
      - name: Find Nuget
        id: findcreatednuget
        run: echo nugetPackageName=$(find . -type f -name '*.nupkg') >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Push to NuGet.org
        run: dotnet nuget push "${{ steps.findcreatednuget.outputs.nugetPackageName }}" --api-key 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 --source source "github"
        shell: bash
